export const ArticleDummy = [
  {
    projectId: 1,
    title: 'title1',
    content: 'content1',
    status: 0,
    view: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    userId: 1,
  },
  {
    articleId: 2,
    title: 'test_title2',
    content: 'test_content2',
    status: 0,
    view: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    userId: 2,
  },
  {
    articleId: 3,
    title: 'test_title3',
    content: 'test_content3',
    status: 0,
    view: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    userId: 3,
  },
  {
    articleId: 4,
    title: 'test_title4',
    content: 'test_content4',
    status: 0,
    view: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    userId: 3,
  },
];
