export const UserDummy = [
  {
    userId: 1,
    email: 'test1@gmail.com',
    password: '1111',
    nickname: 'nickname1',
    profileImg: 'default',
    introduction: null,
    authLevel: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    userId: 2,
    email: 'test2@gmail.com',
    password: '2222',
    nickname: 'nickname2',
    profileImg: 'default',
    introduction: null,
    authLevel: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    userId: 3,
    email: 'test3@gmail.com',
    password: '3333',
    nickname: 'nickname3',
    profileImg: 'default',
    introduction: null,
    authLevel: 0,
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
];
