import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1699120780381 implements MigrationInterface {
    name = 'Migration1699120780381'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`IDX_3c3ab3f49a87e6ddb607f3c494\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_5da3f86a40ce07289424c734c9\` ON \`users\``);
        await queryRunner.query(`CREATE TABLE \`board\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`description\` varchar(255) NOT NULL, \`status\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Projects\` (\`project_id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`user_id\` int UNSIGNED NOT NULL, \`title\` varchar(255) NOT NULL, \`content\` text NOT NULL, \`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, PRIMARY KEY (\`project_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Comments\` (\`comment_id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`comment\` text NOT NULL, \`project_id\` int UNSIGNED NOT NULL, \`user_id\` int UNSIGNED NOT NULL, \`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, PRIMARY KEY (\`comment_id\`, \`project_id\`, \`user_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Users\` (\`user_id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`nickname\` varchar(255) NOT NULL, \`profile_img\` varchar(255) NULL, \`introduction\` varchar(255) NULL, \`authLevel\` int UNSIGNED NOT NULL DEFAULT '0', \`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, UNIQUE INDEX \`IDX_3c3ab3f49a87e6ddb607f3c494\` (\`email\`), UNIQUE INDEX \`IDX_5da3f86a40ce07289424c734c9\` (\`nickname\`), PRIMARY KEY (\`user_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Likes\` (\`project_id\` int UNSIGNED NOT NULL, \`user_id\` int UNSIGNED NOT NULL, PRIMARY KEY (\`project_id\`, \`user_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`articles\` (\`id\` int NOT NULL AUTO_INCREMENT, \`author\` varchar(10) NOT NULL, \`title\` varchar(50) NOT NULL, \`content\` varchar(1000) NOT NULL, \`password\` varchar(255) NOT NULL, \`view\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Articles\` (\`article_id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`user_id\` int UNSIGNED NOT NULL, \`title\` varchar(255) NOT NULL, \`content\` text NOT NULL, \`view\` int NULL DEFAULT '0', \`category_id\` int UNSIGNED NOT NULL, \`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, PRIMARY KEY (\`article_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`Categories\` (\`category_id\` int UNSIGNED NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, PRIMARY KEY (\`category_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`authLevel\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`email\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`introduction\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`nickname\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`profile_img\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`Projects\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD PRIMARY KEY (\`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP COLUMN \`project_id\``);
        await queryRunner.query(`ALTER TABLE \`Users\` DROP COLUMN \`introduction\``);
        await queryRunner.query(`ALTER TABLE \`Users\` DROP COLUMN \`authLevel\``);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`comment_id\` \`comment_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Comments\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Comments\` ADD PRIMARY KEY (\`comment_id\`, \`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`comment_id\` \`comment_id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Comments\` DROP COLUMN \`project_id\``);
        await queryRunner.query(`ALTER TABLE \`Projects\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`Comments\` ADD \`project_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`project_id\` \`comment_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Comments\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Comments\` ADD PRIMARY KEY (\`comment_id\`, \`user_id\`, \`project_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`comment_id\` \`project_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Users\` ADD \`introduction\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`Users\` ADD \`authLevel\` int UNSIGNED NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD \`project_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD PRIMARY KEY (\`user_id\`, \`project_id\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`userId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD UNIQUE INDEX \`IDX_8bf09ba754322ab9c22a215c91\` (\`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`name\` varchar(10) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`Projects\` ADD \`status\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Projects\` ADD \`view\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD \`article_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD PRIMARY KEY (\`user_id\`, \`project_id\`, \`article_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Users\` ADD \`id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Users\` ADD UNIQUE INDEX \`IDX_16d4f7d636df336db11d87413e\` (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`Users\` ADD \`name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Users\` ADD \`phone\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Users\` ADD UNIQUE INDEX \`IDX_f0444b8b5c111257c300932ae0\` (\`phone\`)`);
        await queryRunner.query(`ALTER TABLE \`Users\` ADD \`role\` int UNSIGNED NOT NULL DEFAULT '3'`);
        await queryRunner.query(`ALTER TABLE \`Comments\` ADD \`original_comment_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`Comments\` ADD \`article_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD PRIMARY KEY (\`project_id\`, \`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD PRIMARY KEY (\`project_id\`, \`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD PRIMARY KEY (\`project_id\`, \`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD PRIMARY KEY (\`project_id\`, \`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD PRIMARY KEY (\`article_id\`, \`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD PRIMARY KEY (\`article_id\`, \`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`password\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`password\` varchar(10) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Projects\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`Projects\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`comment_id\` \`comment_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Comments\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Comments\` ADD PRIMARY KEY (\`comment_id\`, \`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`comment_id\` \`comment_id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`comment_id\` \`comment_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Comments\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Comments\` ADD PRIMARY KEY (\`comment_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`comment_id\` \`comment_id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Projects\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`Projects\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`Projects\` ADD CONSTRAINT \`FK_2888c0b921e297a1124e203d91c\` FOREIGN KEY (\`user_id\`) REFERENCES \`Users\`(\`user_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Comments\` ADD CONSTRAINT \`FK_ff2b4ceb89a35315878c06007b3\` FOREIGN KEY (\`project_id\`) REFERENCES \`Projects\`(\`project_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Comments\` ADD CONSTRAINT \`FK_22ec3485cde8dfcd915922addc1\` FOREIGN KEY (\`user_id\`) REFERENCES \`Users\`(\`user_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD CONSTRAINT \`FK_e7bf078b4e3c2c8122abc1b48c7\` FOREIGN KEY (\`user_id\`) REFERENCES \`Users\`(\`user_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD CONSTRAINT \`FK_bc00429378ddbfa066fda7c9511\` FOREIGN KEY (\`project_id\`) REFERENCES \`Projects\`(\`project_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD CONSTRAINT \`FK_5f40470207c73416db5b7363679\` FOREIGN KEY (\`article_id\`) REFERENCES \`Articles\`(\`article_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Comments\` ADD CONSTRAINT \`FK_2cd88affaa3798089b56496325d\` FOREIGN KEY (\`article_id\`) REFERENCES \`Articles\`(\`article_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Articles\` ADD CONSTRAINT \`FK_0f1582549c08cd9c1c6479f6217\` FOREIGN KEY (\`user_id\`) REFERENCES \`Users\`(\`user_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`Articles\` ADD CONSTRAINT \`FK_28294d16bd7d73c91a5e2bd7025\` FOREIGN KEY (\`category_id\`) REFERENCES \`Categories\`(\`category_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`Articles\` DROP FOREIGN KEY \`FK_28294d16bd7d73c91a5e2bd7025\``);
        await queryRunner.query(`ALTER TABLE \`Articles\` DROP FOREIGN KEY \`FK_0f1582549c08cd9c1c6479f6217\``);
        await queryRunner.query(`ALTER TABLE \`Comments\` DROP FOREIGN KEY \`FK_2cd88affaa3798089b56496325d\``);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP FOREIGN KEY \`FK_5f40470207c73416db5b7363679\``);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP FOREIGN KEY \`FK_bc00429378ddbfa066fda7c9511\``);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP FOREIGN KEY \`FK_e7bf078b4e3c2c8122abc1b48c7\``);
        await queryRunner.query(`ALTER TABLE \`Comments\` DROP FOREIGN KEY \`FK_22ec3485cde8dfcd915922addc1\``);
        await queryRunner.query(`ALTER TABLE \`Comments\` DROP FOREIGN KEY \`FK_ff2b4ceb89a35315878c06007b3\``);
        await queryRunner.query(`ALTER TABLE \`Projects\` DROP FOREIGN KEY \`FK_2888c0b921e297a1124e203d91c\``);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Projects\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`Projects\` CHANGE \`created_at\` \`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`comment_id\` \`comment_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Comments\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Comments\` ADD PRIMARY KEY (\`comment_id\`, \`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`comment_id\` \`comment_id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`comment_id\` \`comment_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Comments\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Comments\` ADD PRIMARY KEY (\`comment_id\`, \`user_id\`, \`project_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`comment_id\` \`comment_id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Projects\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`Projects\` CHANGE \`created_at\` \`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`password\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`password\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD PRIMARY KEY (\`user_id\`, \`project_id\`, \`article_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD PRIMARY KEY (\`user_id\`, \`project_id\`, \`article_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD PRIMARY KEY (\`user_id\`, \`project_id\`, \`article_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD PRIMARY KEY (\`user_id\`, \`project_id\`, \`article_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD PRIMARY KEY (\`user_id\`, \`project_id\`, \`article_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD PRIMARY KEY (\`user_id\`, \`project_id\`, \`article_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Comments\` DROP COLUMN \`article_id\``);
        await queryRunner.query(`ALTER TABLE \`Comments\` DROP COLUMN \`original_comment_id\``);
        await queryRunner.query(`ALTER TABLE \`Users\` DROP COLUMN \`role\``);
        await queryRunner.query(`ALTER TABLE \`Users\` DROP INDEX \`IDX_f0444b8b5c111257c300932ae0\``);
        await queryRunner.query(`ALTER TABLE \`Users\` DROP COLUMN \`phone\``);
        await queryRunner.query(`ALTER TABLE \`Users\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`Users\` DROP INDEX \`IDX_16d4f7d636df336db11d87413e\``);
        await queryRunner.query(`ALTER TABLE \`Users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD PRIMARY KEY (\`user_id\`, \`project_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP COLUMN \`article_id\``);
        await queryRunner.query(`ALTER TABLE \`Projects\` DROP COLUMN \`view\``);
        await queryRunner.query(`ALTER TABLE \`Projects\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`name\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP INDEX \`IDX_8bf09ba754322ab9c22a215c91\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD PRIMARY KEY (\`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP COLUMN \`project_id\``);
        await queryRunner.query(`ALTER TABLE \`Users\` DROP COLUMN \`authLevel\``);
        await queryRunner.query(`ALTER TABLE \`Users\` DROP COLUMN \`introduction\``);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`project_id\` \`comment_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Comments\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Comments\` ADD PRIMARY KEY (\`comment_id\`, \`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`comment_id\` \`project_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Comments\` DROP COLUMN \`project_id\``);
        await queryRunner.query(`ALTER TABLE \`Projects\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`Comments\` ADD \`project_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`comment_id\` \`comment_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Comments\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Comments\` ADD PRIMARY KEY (\`comment_id\`, \`project_id\`, \`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Comments\` CHANGE \`comment_id\` \`comment_id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`Users\` ADD \`authLevel\` int UNSIGNED NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`Users\` ADD \`introduction\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD \`project_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`Likes\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`Likes\` ADD PRIMARY KEY (\`project_id\`, \`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`Projects\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`user_id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD PRIMARY KEY (\`user_id\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`user_id\` \`user_id\` int UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updated_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`profile_img\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`nickname\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`introduction\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`authLevel\` int UNSIGNED NOT NULL DEFAULT '0'`);
        await queryRunner.query(`DROP TABLE \`Categories\``);
        await queryRunner.query(`DROP TABLE \`Articles\``);
        await queryRunner.query(`DROP TABLE \`articles\``);
        await queryRunner.query(`DROP TABLE \`Likes\``);
        await queryRunner.query(`DROP INDEX \`IDX_5da3f86a40ce07289424c734c9\` ON \`Users\``);
        await queryRunner.query(`DROP INDEX \`IDX_3c3ab3f49a87e6ddb607f3c494\` ON \`Users\``);
        await queryRunner.query(`DROP TABLE \`Users\``);
        await queryRunner.query(`DROP TABLE \`Comments\``);
        await queryRunner.query(`DROP TABLE \`Projects\``);
        await queryRunner.query(`DROP TABLE \`board\``);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_5da3f86a40ce07289424c734c9\` ON \`users\` (\`nickname\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_3c3ab3f49a87e6ddb607f3c494\` ON \`users\` (\`email\`)`);
    }

}
